name: starter
description: "Flutter starter project inspired by PlugFox"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0
  flutter: ^3.38.0

workspace:
  - packages/db
  - packages/l10n
  - packages/ui

dependencies:
  async: any
  collection: any
  control: ^0.2.0
  crypto: ^3.0.7
  db: 
    path: packages/db
  equatable: ^2.0.7
  file_picker: ^10.3.7 # https://github.com/miguelpruivo/flutter_file_picker/issues/1602
  firebase_analytics: ^12.0.4
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  flutter_email_sender: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_md: ^0.0.8
  flutter_web_plugins:
    sdk: flutter
  google_sign_in: ^7.2.0
  http: ^1.6.0
  in_app_purchase: ^3.2.3
  intl: any
  l: ^5.0.0
  l10n:
    path: packages/l10n
  matomo_tracker: ^6.1.0
  meta: any
  octopus: ^0.0.9
  path: any
  path_provider: ^2.1.5
  pdf: ^3.11.3
  platform_info: ^5.0.0
  posthog_flutter: ^5.0.0
  printing: ^5.14.2
  pub_semver: ^2.2.0
  sentry_flutter: ^9.8.0
  shared_preferences: ^2.5.3
  sqlite3_flutter_libs: ^0.5.40
  ui:
    path: packages/ui
  url_launcher: ^6.3.2
  web: ^1.1.1


dev_dependencies:
  build_runner: ^2.10.4
  clock: ^1.1.2
  fake_async: ^1.3.3
  flutter_gen_runner: ^5.12.0
  flutter_test:
    sdk: flutter
  html: ^0.15.6
  integration_test:
    sdk: flutter
  pubspec_generator: ^5.0.0
  sentry_dart_plugin: ^3.2.0
  very_good_analysis: ^10.0.0

dependency_overrides:
  meta: ^1.17.0

flutter:
  uses-material-design: true

  shaders:
    - assets/shaders/shimmer.frag

