name: db
description: Database
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

resolution: workspace

dependencies:
  drift: ^2.29.0

dev_dependencies:
  build_runner: ^2.10.4
  drift_dev: ^2.29.0
